// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkslyzkkgqsylxnjptob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrc2x5emtrZ3FzeWx4bmpwdG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDAzMTksImV4cCI6MjA3MzI3NjMxOX0.Nb-_ADuC8JjZy3OKVuN34nXzanOXz0rTu0QDUrTAG20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});